source 'https://github.com/CocoaPods/Specs.git'
target 'JBWebViewController' do
use_frameworks!
pod 'ARChromeActivity', '~> 1.0'
pod 'ARSafariActivity', '~> 0.0.1'
pod 'NJKWebViewProgress', '~> 0.2'
end
